### ISSUE TITLE
Stunningly

### ISSUE THREAD

**Issue by VentorNew** [heisenshark/blender-krita-link-plugin#10]
This is one hell of an awesome addon! I can't describe how glad I am that I decided to look for an addon like this!
And it even seems to work. As the warning said, you need to use Krita 5.2.2, and Blender works with version 4.0.

**Comment by heisenshark** [comment]
Nice to hear that, but the issues tab is place to share issues, if you run into any please share them here. For less specific conversations and comments there is a krita-artists posts [here](https://krita-artists.org/t/blender-krita-link-plugin-for-texture-editing-in-krita/83980).
