### ISSUE TITLE
Wrong Installation Guide

### ISSUE THREAD

**Issue by DartDeaDia** [heisenshark/blender-krita-link-plugin#13]
Hi, I can't install this plugin because the installation guide specifies the wrong locations and some files are missing.

I managed to install the addon in Blender, but I placed the `BlenderKritaLink` folder in the `blender/version/scripts/addons_core/`, because it didn't work when I put it in `blender/version/scripts/addons/`

But the Krita Part I didn't manage, because the `KritaBlenderDesktop.html` file is missing

**Comment by heisenshark** [comment]
oh, I made a typo, of course I meant `KritaBlenderLink.desktop` file in the repo root

as for blender stuff they recently changed the way they make addons extensions as I see [there](https://docs.blender.org/manual/en/latest/extensions/addons.html) 

so the blender addon is legacy addon and must be installed as such, I recommend installation trough additional script directory with correct structre as described [here](https://docs.blender.org/manual/en/latest/editors/preferences/addons.html#prefs-extensions-install-legacy-addon)

thanks for the bug report and I'm sure I will try make the installation less painfull in the future

**Comment by DartDeaDia** [comment]
Thanks, I hope the installation will be as easy as in the [Pribambase](https://github.com/AlienPolygon/pribambase).
This is a similar plugin to yours, but it synchronizes Blender with Aseprite.
Maybe you would find something useful in its source code

**Comment by heisenshark** [comment]
I'm well aware of Pribambase, kinda sad that the original repo went down recently.

anyway, closing the issue as its resolved hopefully
