### ISSUE TITLE
Random blender viewport breakages

### ISSUE THREAD

**Issue by radicalaction** [heisenshark/blender-krita-link-plugin#15]
![artifacts](https://github.com/user-attachments/assets/55bbd311-f5d3-4bff-8331-48508c7111a3)
These usually happen when opening Preferences menu in blender. It's either that or just every viewport turns black until I restart blender. Blender remains responsive and lets me save files and stuff. I'm opening an issue here because I notice this specific behavior only when Blender Krita Link addon is active.
GPU is intel HD 620, mesa drivers

**Comment by radicalaction** [comment]
bottom half looks like one of these "today's mission" videos with green and magenta dudes lawl

**Comment by heisenshark** [comment]
does this issue occurs in 4.1 blender version?

**Comment by radicalaction** [comment]
@heisenshark This occurs in 4.2.1. I'm not sure about 4.1. You suggest me to test it with 4.1?

**Comment by heisenshark** [comment]
@radicalaction yes, its the version that I tested after all

**Comment by radicalaction** [comment]
@heisenshark Okay, I will try

**Comment by radicalaction** [comment]
@heisenshark nah, still happens. Even on 4.1.1. This time it occured when I switched workspace to one with blender. Guess it's not about opening Preferences menu.

**Comment by heisenshark** [comment]
ok, will investigate what the plugin does that can produce artifacts on igpu, tho it might be hard to replicate

things that may cause some stuff:
- plugin is updating  its panel frequently
- plugin in blender is checking for uvs in blender so that might make a difference
- plugin is refreshing most of blender windows on image send to rerender 3D views and stuff

maybe 0.1 ver does not have this problem, but it feels very specific 

uncommenting things in class _PT_BlenderKritaLinkPanel, UvWatch or ImageManager could help

**Comment by radicalaction** [comment]
@heisenshark 
```
panel instantiated
panel instantiated
panel instantiated
panel instantiated
panel instantiated
panel instantiated
panel instantiated
panel instantiated
{'type': 'REFRESH', 'depth': 'U8', 'requestId': 2137, 'data': {'size': [4096, 4096]}}
refresh initiated 67108864
UPDATING MESSAGE:  got The Image
refresh initiated
hello from mirror_image
hello from mirror_image 1.33514404296875e-05
hello from mirror_image 67108864 67108864 4096 4096
bef reshaped [0 0 0 ... 0 0 0] 67108864 4096.0 4096.0
reshaped
flipped
resized
reshaped2
hello from mirror_image 67108864 4096 0.2615354061126709
0 0 <class 'numpy.uint8'>
0.0 0.0
hello from mirror_image 1.1699833869934082
hello from mirror_image, packed, alfa changed  1.170069694519043
refresh complete
UPDATING MESSAGE:  connected
Saved session recovery to "/tmp/quit.blend"
cleanup
sending close

Blender quit
/usr/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/krita-blender65431': [Errno 2] No such file or directory: '/krita-blender65431'
  warnings.warn('resource_tracker: %r: %s' % (name, e))
```
This is from blender run in terminal. I assume that it got broken somewhere here. 
> uncommenting things in class _PT_BlenderKritaLinkPanel, UvWatch or ImageManager could help

Okay, thanks, I will try.

**Comment by radicalaction** [comment]
4.1.1 on the other hand, doesn't log anything unusual, it just breaks quietly:
```
panel instantiated
panel instantiated
...
panel instantiated
panel instantiated
Saved session recovery to "/tmp/quit.blend"
cleanup
accepting
UPDATING MESSAGE:  connected
connection accepted
UPDATING MESSAGE:  connected
close
close
UPDATING MESSAGE:  closed

Blender quit
```

**Comment by radicalaction** [comment]
Sorry! "I notice this specific behavior only when Blender Krita Link addon is active." was just a coincidence, this issue is not related to your plugin.
