### ISSUE TITLE
where Plugin_native_addition_Windows should be placed?

### ISSUE THREAD

**Issue by chenpaner** [heisenshark/blender-krita-link-plugin#16]
Hi,
    Can you elaborate on where Plugin_native_addition_Windows should be placed? I tested multiple locations, and none of them generated a selection.Does it function to establish selection through UV like in your video?

**Comment by heisenshark** [comment]
Just drop the contents of zip file directly into the krita installation like .../programfiles/krita and you should be good to go. You can even see that the folders in zip directly corespond to the folders in the installation like lib and share 

Yes the native addition is for creating selection only

**Comment by chenpaner** [comment]
Thank You！
